/// Supported intent types for the Guardian Assistant (V1)
enum IntentType {
  showBalances,
  showRisks,
  scanApprovals,
  revokeApproval,
  sendAsset,
  receiveAsset,
  swapAsset,
  showAddress,
  showHistory,
  showWalletCards,
  openAddressBook,
  openWalletSettings,
  openMarket,
  openSecurityCenter,
  buyAsset,
  sellAsset,
  unknown,
}

/// The mode for swap calculation
enum AmountMode { exactIn, exactOut }

/// Where an operation originated — determines which limits apply.
/// wallet = plain wallet send/swap (only wallet send/swap/approve limits).
/// market = trading / CEX / AI / automation (trading limits apply).
enum IntentOrigin { wallet, market }

/// Structured representation of a parsed user command.
class IntentData {
  final IntentType type;

  /// Token symbol, e.g. "USDT", "BNB"
  final String? tokenSymbol;

  /// Target address for send operations
  final String? toAddress;

  /// Amount for send operations or swap exact amount.
  final double? amount;

  /// Raw amount in Wei (more precise).
  final BigInt? rawAmount;

  /// Source token symbol for swap.
  final String? sourceTokenSymbol;

  /// Source token contract address for swap.
  final String? sourceTokenAddress;

  /// Target token symbol for swap.
  final String? targetTokenSymbol;

  /// Target token contract address for swap.
  final String? targetTokenAddress;

  /// Swap mode: exact input vs exact output.
  final AmountMode? amountMode;

  /// Slippage tolerance in basis points.
  final int? slippageBps;

  /// Token decimals for precise amount conversion (e.g. USDC=6, WBTC=8).
  /// Null means unknown — execution MUST error, not assume 18.
  final int? sourceTokenDecimals;
  final int? targetTokenDecimals;

  /// Original raw input from the user
  final String rawInput;

  /// Optional context for where this intent came from (Phase 6 automation engine trigger marker)
  final String? sourceTrigger;

  /// Whether the amount represents token quantity (e.g. 2 SOL) or USD value (e.g. 20 USDT)
  final bool isQuantity;

  /// Where this operation originated — decides which limits apply
  /// (wallet limits vs trading limits). Defaults to market (safe: trading
  /// limits apply unless explicitly a plain wallet action).
  final IntentOrigin origin;

  /// Returns true if this intent was artificially generated by the automation framework
  bool get isAutomated => sourceTrigger != null;

  const IntentData({
    required this.type,
    required this.rawInput,
    this.tokenSymbol,
    this.toAddress,
    this.amount,
    this.rawAmount,
    this.sourceTokenSymbol,
    this.sourceTokenAddress,
    this.targetTokenSymbol,
    this.targetTokenAddress,
    this.amountMode,
    this.slippageBps,
    this.sourceTokenDecimals,
    this.targetTokenDecimals,
    this.sourceTrigger,
    this.isQuantity = false,
    this.origin = IntentOrigin.market,
  });

  /// Whether this intent requires execution (as opposed to just reading data)
  bool get isExecutionIntent =>
      type == IntentType.sendAsset ||
      type == IntentType.revokeApproval ||
      type == IntentType.swapAsset ||
      type == IntentType.buyAsset ||
      type == IntentType.sellAsset;

  /// Whether this intent is purely informational
  bool get isInformationalIntent =>
      type == IntentType.showBalances ||
      type == IntentType.receiveAsset ||
      type == IntentType.showAddress ||
      type == IntentType.showHistory ||
      type == IntentType.showWalletCards ||
      type == IntentType.openAddressBook ||
      type == IntentType.openWalletSettings ||
      type == IntentType.openMarket ||
      type == IntentType.openSecurityCenter ||
      type == IntentType.showRisks ||
      type == IntentType.scanApprovals;

  @override
  String toString() =>
      'IntentData(type: $type, token: $tokenSymbol, amount: $amount, to: $toAddress)';

  /// Creates a minimal IntentData for system/internal operations (e.g. EPK revoke initiated programmatically)
  factory IntentData.empty() => const IntentData(
        type: IntentType.unknown,
        rawInput: 'system',
      );

  factory IntentData.fromJson(Map<String, dynamic> json) {
    final params = json['params'] as Map<String, dynamic>? ?? json;

    // rawAmount stored as string to avoid JSON number precision loss.
    final rawAmountStr = params['rawAmount']?.toString();
    final BigInt? rawAmount =
        rawAmountStr != null ? BigInt.tryParse(rawAmountStr) : null;

    return IntentData(
      type: IntentType.values.firstWhere(
        (e) => e.name == json['type'],
        orElse: () => IntentType.unknown,
      ),
      rawInput: json['rawInput']?.toString() ?? '',
      tokenSymbol: params['tokenSymbol'] ?? params['symbol'],
      toAddress: params['toAddress'] ?? params['address'],
      amount: (params['amount'] as num?)?.toDouble(),
      rawAmount: rawAmount,
      sourceTokenSymbol: params['sourceTokenSymbol'] ?? params['sourceSymbol'],
      sourceTokenAddress: params['sourceTokenAddress']?.toString(),
      targetTokenSymbol: params['targetTokenSymbol'] ?? params['targetSymbol'],
      targetTokenAddress: params['targetTokenAddress']?.toString(),
      amountMode: params['amountMode'] == 'exactOut'
          ? AmountMode.exactOut
          : (params['amountMode'] == 'exactIn' ? AmountMode.exactIn : null),
      slippageBps: _parseInt(params['slippageBps']),
      sourceTokenDecimals: _parseInt(params['sourceTokenDecimals']),
      targetTokenDecimals: _parseInt(params['targetTokenDecimals']),
      sourceTrigger: params['sourceTrigger']?.toString(),
      isQuantity: params['isQuantity'] == true,
      origin: params['origin'] == 'wallet'
          ? IntentOrigin.wallet
          : IntentOrigin.market,
    );
  }

  Map<String, dynamic> toJson() => {
        'type': type.name,
        'rawInput': rawInput,
        'params': {
          'tokenSymbol': tokenSymbol,
          'toAddress': toAddress,
          'amount': amount,
          'rawAmount': rawAmount?.toString(), // String for BigInt safety
          'sourceTokenSymbol': sourceTokenSymbol,
          'sourceTokenAddress': sourceTokenAddress,
          'targetTokenSymbol': targetTokenSymbol,
          'targetTokenAddress': targetTokenAddress,
          'amountMode': amountMode?.name,
          'slippageBps': slippageBps,
          'sourceTokenDecimals': sourceTokenDecimals,
          'targetTokenDecimals': targetTokenDecimals,
          'sourceTrigger': sourceTrigger,
          'isQuantity': isQuantity,
          'origin': origin.name,
        }
      };

  /// Robust int parser: handles both [num] and [String] from JSON/LLM.
  static int? _parseInt(dynamic v) {
    if (v is num) return v.toInt();
    return int.tryParse(v?.toString() ?? '');
  }

  IntentData copyWith({
    IntentType? type,
    String? rawInput,
    String? tokenSymbol,
    String? toAddress,
    double? amount,
    BigInt? rawAmount,
    String? sourceTokenSymbol,
    String? sourceTokenAddress,
    String? targetTokenSymbol,
    String? targetTokenAddress,
    AmountMode? amountMode,
    int? slippageBps,
    int? sourceTokenDecimals,
    int? targetTokenDecimals,
    String? sourceTrigger,
    bool? isQuantity,
    IntentOrigin? origin,
  }) {
    return IntentData(
      type: type ?? this.type,
      rawInput: rawInput ?? this.rawInput,
      tokenSymbol: tokenSymbol ?? this.tokenSymbol,
      toAddress: toAddress ?? this.toAddress,
      amount: amount ?? this.amount,
      rawAmount: rawAmount ?? this.rawAmount,
      sourceTokenSymbol: sourceTokenSymbol ?? this.sourceTokenSymbol,
      sourceTokenAddress: sourceTokenAddress ?? this.sourceTokenAddress,
      targetTokenSymbol: targetTokenSymbol ?? this.targetTokenSymbol,
      targetTokenAddress: targetTokenAddress ?? this.targetTokenAddress,
      amountMode: amountMode ?? this.amountMode,
      slippageBps: slippageBps ?? this.slippageBps,
      sourceTokenDecimals: sourceTokenDecimals ?? this.sourceTokenDecimals,
      targetTokenDecimals: targetTokenDecimals ?? this.targetTokenDecimals,
      sourceTrigger: sourceTrigger ?? this.sourceTrigger,
      isQuantity: isQuantity ?? this.isQuantity,
      origin: origin ?? this.origin,
    );
  }
}

/// The action the IntentRouter decided on — what should happen next.
/// Router does NOT execute anything directly. It returns this to ExecutionService.
class IntentAction {
  final IntentData intent;

  /// Whether this action needs to go through the policy engine
  final bool requiresExecution;

  /// Whether user confirmation should be displayed in UI before execution.
  /// TODO(Phase 4): This flag should also be driven by PolicyEngine output,
  /// not just by the router — so policy can override and force confirmation dynamically.
  final bool requiresConfirmation;

  const IntentAction({
    required this.intent,
    required this.requiresExecution,
    this.requiresConfirmation = false,
  });
}
